#define CLIENT_IO_ERROR -1
#define CLIENT_TIMEOUT_ERROR -2
#define HOST_IO_ERROR -3
#define HOST_TIMEOUT_ERROR -4

#define NO_CONTENT_LENGTH_OR_TRANSFER_ENCODING -5
#define IS_TRANSFER_ENCODING -6
#define IS_NOT_GET -7
#define NO_HOST -8

#define FILE_CANNOT_BE_CREATED -1
#define FILE_IO_ERROR -2
#define FILE_CANNOT_BE_RENAMED -3
#define FILE_NOT_EXIST -4
#define CACHE_CONFLICT -5